name: test-pr

on:
  pull_request:

permissions:
  contents: read

concurrency:
  group: 'test-pr'
  cancel-in-progress: false

env:
  NODE_VERSION: '20.x'

jobs:
  test-pr:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup nodejs ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: npm ci
        run: npm ci

      - name: lint
        run: npm run lint
